apiVersion: v1
kind: Pod
metadata:
  name: os
  labels: 
      app: os
spec:
  containers:
  - name: busybox-c
    image: busybox 
    command: ["sleep"]
    args: ["60"]
    env:
      - name: MYSQL_HOME
        valueFrom:
          configMapKeyRef:
            name: db-configmap
            key: db.mysql_home

      - name: MYSQL_PWD
        valueFrom:
          configMapKeyRef:
            name: db-configmap
            key: db.mysql_pwd

      - name: MYSQL_TCP_PORT
        valueFrom:
          configMapKeyRef:
            name: db-configmap
            key: db.mysql_tcp_port


       

