apiVersion: v1
kind: Pod
metadata:
  name: os
  labels: 
      app: os
spec:
  containers:
  - name: busybox-c
    image: busybox 
    command: ["sleep"]
    args: ["60"]
    env:
      - name: PASSWD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: password
       

