apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-vol-rc
  labels: 
    tier: dev 
spec:
    replicas: 2
    selector: 
       app: httpd-vol-app 
    template:
     metadata:
       name: httpd_vol_pod 
       labels:
         app: httpd-vol-app 
     spec:
       containers:
       - name: httpd 
         image: httpd:2.4
         command: ["mkdir"]
         args: ["/cache"]
         volumeMounts:
                 - name: cache-volume
                   mountPath: /cache
         ports: 
         - containerPort: 80
       volumes:
       - name: cache-volume
         hostPath:
                  path: /hostdir-data
                  type: Directory
       
