apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv0003claim
spec:
  selector:
    matchLabels:
      # volume: pv0003
      pv-type: nfs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
      requests:
        storage: 1Mi
