kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
   name: pv0
   labels:
    pv-type: nfs
  spec:
   capacity:
    storage: 1Gi
   volumeMode: Filesystem
   accessModes:
    - ReadWriteOnce
   persistentVolumeReclaimPolicy: Recycle
#  storageClassName: manual
   mountOptions:
    - hard
    - nfsvers=4.1
   nfs:
    path: /exports/pv-0
    server: 192.168.0.235
- apiVersion: v1
  kind: PersistentVolume
  metadata:
   name: pv1
   labels:
    pv-type: nfs
  spec:
   capacity:
    storage: 1Gi
   volumeMode: Filesystem
   accessModes:
    - ReadWriteOnce
   persistentVolumeReclaimPolicy: Recycle
#  storageClassName: manual
   mountOptions:
    - hard
    - nfsvers=4.1
   nfs:
    path: /exports/pv-1
    server: 192.168.0.235
- apiVersion: v1
  kind: PersistentVolume
  metadata:
   name: pv2
   labels:
    pv-type: nfs
  spec:
   capacity:
    storage: 1Gi
   volumeMode: Filesystem
   accessModes:
    - ReadWriteOnce
   persistentVolumeReclaimPolicy: Recycle
#  storageClassName: manual
   mountOptions:
    - hard
    - nfsvers=4.1
   nfs:
    path: /exports/pv-2
    server: 192.168.0.235