apiVersion: batch/v1
kind: Job
metadata:
  name: os
  labels: 
      app: os
spec:
  completions: 6
  parallelism: 2
  template:
      spec:
        containers:
        - name: busybox-c
          image: busybox 
          command: ["sleep"]
          args: ["60"]
        restartPolicy: Never

